### ISSUE TITLE
Change DAG-DBOR to DAG-PB for cid implementation

### ISSUE THREAD

**Issue by xinaxu** [decentralized-identity/decentralized-web-node#101]
Capture what we have discussed - 
The cid for the data will be using DAG-PB with chunking (same as ipfs add). For any object, it will need to be converted to file/byte array first. i.e. JSON object needs to be stringified first. The data field will be populated with base64 encoded byte array of the actual data.
The cid for the request will also be DAG-PB

**Comment by csuwildcat** [comment]
Tagging @oed for awareness and feedback

**Comment by oed** [comment]
Hm, this means that you will essentially only use ipld as a file store
(which might be right for your use case). However, you won't be able to
leverage newer and more interesting features such as graphsync.

--
*Joel Thorstensson *
Co-founder / CTO

[image: 3Box Labs] <https://3boxlabs.com>

**Comment by xinaxu** [comment]
That is true. I think as we've discussed with @csuwildcat , we don't think we will ever need to use any advanced feature for forseable future.

**Comment by xinaxu** [comment]
@csuwildcat 
Adding more details for how the CID should be generated.
We should use the options:
chunker - default - size-262144
cidVersion - not default - 1
hashAlg - default - sha2-256

https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md#options
