### ISSUE TITLE
Incorrect text for Message failed authorization requirements

### ISSUE THREAD

**Issue by alanhkarp** [decentralized-identity/decentralized-web-node#113]
Response shows text "OK" instead of the recommended "The message failed authorization requirements".

**Comment by andorsk** [comment]
@alanhkarp we're doing some spring cleaning and addressing all the issues that have not been addressed for a while. Our apologies for not getting to this sooner. Could you clarify where you saw this message?

**Comment by alanhkarp** [comment]
Sorry, but I don't recall.  It's my fault.  I should have included a reference in my comment.

**Comment by andorsk** [comment]
No worries. We'll try to keep an eye on these closer from now on!
