### ISSUE TITLE
Are responses sync, async, or both?

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/decentralized-web-node#120]
### Problem
The spec doesn't indicate whether responses are supposed to be sync, async, or circumstantially either. 

I can see use-cases for both sync and async responses though supporting both will be impossible at times depending on the chosen transport layer (e.g. websockets)

**Comment by mistermoe** [comment]
Relevant: https://github.com/decentralized-identity/decentralized-web-node/issues/165#issuecomment-1154365462

**Comment by LiranCohen** [comment]
It depends on the interfaces that are being invoked.

In some cases there will be sync request/response, and others will be more of stream like web sockets. Since the DWN is transport agnostic it really depends on how it is invoked.
