### ISSUE TITLE
Expected runtime environments

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/decentralized-web-node#124]
What environments are hubs expected to run in?

The first image in the spec implies that hubs can run "locally" and in "the cloud". Local is presumably mobile devices and browsers. The spec does not address the fact that local hubs will likely have restrictions that prevent them from running as the spec states.

For example, if a local hub is running within a mobile app, is the expectation that the mobile app be running a server that can accept requests from anyone in the world? I realize that hubs are transport agnostic, but it seems to be the case that hubs necessitate listening over _some_ transport. 

I think it might be worth clarifying the distinction

**Comment by csuwildcat** [comment]
Definitely worthwhile noting limitations of environments, will do a PR for this.

**Comment by agropper** [comment]
I see this as a delegation issue, not a transport.

If we presume a DID or a directory that points to a service endpoint as the
universal foundation, then the transport is subsumed in the service
endpoint pointer. The service endpoint could, optionally, be a mediator
that points to the hub but the hub transport can be different as long as
the mediator is willing to translate.

Building hubs and directories on top of DIDcomm or any other single
messaging protocol is possible but seems impractical to those of us that
see delegation as the core decentralization issue.

**Comment by mweel1** [comment]
I see the delegation issue here also.  If I have 2 nodes, 1 running on the cloud and 1 running on my mobile.  I'm always going to want the cloud to handle requests and pub/sub messaging.  My mobile has no value in retrying publications, and taking requests.

**Comment by andorsk** [comment]
@csuwildcat bringing this back from the dead.

**Comment by andorsk** [comment]
Thanks! @csuwildcat

**Comment by andorsk** [comment]
Thanks! @csuwildcat! Was there a PR related to this? Just so those following this thread can tune into relevant work that resolves this?
