### ISSUE TITLE
Attestation field needs explanation

### ISSUE THREAD

**Issue by alanhkarp** [decentralized-identity/decentralized-web-node#141]
The example in Section 12.4.1 shows an attestation property under descriptor.ability.conditions that needs additional explanation to distinguish it from the top level attestation property.

**Comment by andorsk** [comment]
Does https://identity.foundation/decentralized-web-node/spec/#signed-data address this concern?

**Comment by alanhkarp** [comment]
I can't be sure what problem I saw without access to what was there before, but what's there now looks fine.
