### ISSUE TITLE
as a developer, I can follow docs to run the reference implmentation, so I can test it out and then contribute improvements or passing test-suites

### ISSUE THREAD

**Issue by gobengo** [decentralized-identity/decentralized-web-node#144]
#user-story

Acceptance Criteria:
* Anyone can find documentation at https://github.com/decentralized-identity/decentralized-web-node/tree/main/packages/implementations/javascript , and the result of following the instructions is this software running on the developer's machine

Even better:
* This should work:
    ```
    git clone git@github.com:decentralized-identity/decentralized-web-node.git && cd decentralized-web-node
    npm i
    # -w value corresponds to https://github.com/decentralized-identity/decentralized-web-node/blob/main/packages/implementations/javascript/package.json#L2
    npm -w identity-hub start
    ````

Inspiration:
* https://github.com/textileio/powergate#installation
* https://github.com/web3-storage/web3.storage/tree/main/packages#build-and-run-locally

**Comment by csuwildcat** [comment]
@gobengo yes, you're right, sorry for neglecting the code in this repo - our implementation is here (which we would be willing to donate, per the thinking of the WG): https://github.com/TBD54566975/dwn-sdk-js

**Comment by csuwildcat** [comment]
ACTION: Will remove janky early prototype and point to other implementations (e.g. https://github.com/TBD54566975/dwn-sdk-js)

**Comment by andorsk** [comment]
@csuwildcat can this be closed?

**Comment by andorsk** [comment]
@csuwildcat following up here. OK to close?
