### ISSUE TITLE
Define the difference between local key-empowered nodes with remote nodes

### ISSUE THREAD

**Issue by mwherman2000** [decentralized-identity/decentralized-web-node#152]
The term "local node" appears in the Topology diagram but is not mentioned in the rest of the specification: https://identity.foundation/decentralized-web-node/spec/#topology

A _local node_ appears to be a key concept (i.e. different from a regular node - appearing at the top of the Topology diagram).  

The key concepts in the Topology diagram should be described (as named) in the text that follows the diagram.

**Comment by csuwildcat** [comment]
This is because the nodes aren't technically different, it's just a diagram indicating you can run them locally on your devices.

**Comment by mwherman2000** [comment]
Then what is the difference between "Bob's Node" and "Bob's local Node"?
This needs to be clarified in the diagram and/or the description that follows the diagram. 

This ties in with issue https://github.com/decentralized-identity/decentralized-web-node/issues/151 and the two diagram notations:
- Bob's Node relays Alice's message [to Bob's local Node].
- Alice's Node relays Bob's message [to Alice's local Node].

1. How is this message relay functionality setup? ...especially given DWN can't run any custom code.
2. What does it mean to _relay a message_?  
3. How is _relaying a message_ different from other types of DWN message transfers (e.g. _sending a message_, _sending a response_, etc.)?

As a specification, these points need to be made perfectly clear.

**Comment by mwherman2000** [comment]
> This is because the nodes aren't technically different, it's just a diagram indicating you can run them locally on your devices.

The Topology diagram needs to clarify each _local node_ runs or resides _on the device_.  The way the diagram is currently drawn and labeled, it appears the device is the local node.  In addition, there needs to be someplace on the device where code runs (e.g. a Decentralized Web App (DWA) ...or something explicit like that. 

The questions in the previous post still need to be answered.

**Comment by csuwildcat** [comment]
Changed the title to reflect a broader scope.

**Comment by LiranCohen** [comment]
I took a first pass at this:
https://github.com/decentralized-identity/decentralized-web-node/pull/172

Could probably be a little bit better, not sure if the name "relay node" and "local node" are the best. Maybe we can discuss further what they could be.

**Comment by mweel1** [comment]
Aren't messaging technically being replicated when they are persisted to other nodes?  Relay sounds like nodes are acting as a proxy?

**Comment by andorsk** [comment]
This will be addressed in the companion guide. https://github.com/decentralized-identity/decentralized-web-node/blob/main/docs/companion_guide.md#example-deployment-simple. I will be adding more clarity to this section later, but agreed this should be cleared up here.

**Comment by andorsk** [comment]
@csuwildcat can I assign this to me, to address in the companion guide?

**Comment by csuwildcat** [comment]
@andorsk sure, though there's no real definition needed, because keys being present outside but adjacent to an instance that are being used by some other software doesn't actually change anything about the DWN itself. Good for a guide, but no need for spec text.

**Comment by andorsk** [comment]
Yep. Agreed here. Note the PR above that describes this for clarification.

**Comment by andorsk** [comment]
Discussed on DIF:

Merge #225 was done. Closing this issue.
