### ISSUE TITLE
`requestId` cannot be a requirement for Response Objects

### ISSUE THREAD

**Issue by mistermoe** [decentralized-identity/decentralized-web-node#165]
Regarding response objects, The spec currently states that:

>The object MUST include an requestId property, and its value MUST be the [RFC4122] UUID Version 4 string from the requestId property of the Request Object it is in response to.

If the incoming request doesn't have a `requestId` (which would be a request- level error as defined in section 9.2.3) then the respective response can't have one either. 

I'm not certain as to what the benefits/intended purpose behind `requestId` are, but it seems a bit strange to auto-generate one for a response if the request didn't have one to begin with; especially since it originates from the sender.

@csuwildcat do you remember why you chose to include `requestId` as a property originating from the sender? I don't suspect it's supposed to act as a nonce. Typically, request ids are generated by a receiving server for the purposes of trace logs. A few practical uses for `requestId` on both the sending and receiving side would be super helpful. 

I'm leaning towards making an argument in favor of either getting rid of them or having them originate from the receiving DWN. Will wait to flesh that out after hearing back from you

Until then, the simplest workaround that comes to mind is to explicitly set `requestId`to `null` in the response if there wasn't one in the respective request

**Comment by csuwildcat** [comment]
@mistermoe now that we have a nonce requirement for literally all objects, it's probably safe to use drop requestId. The reason we had the sender specify this initially was so async responses could be associated with requests, because how else would a sender know what any random response payload was in relation to?

**Comment by csuwildcat** [comment]
Both `requestId` and `messageId` have been eliminated in favor of a simplified approach to sync request/response. This is reflected in the current version of the spec.

**Comment by mweel1** [comment]
I really feel this needs be an asynchronous process, and not attacking this now will be a major roadblock in the future.

If done right it will feel synchronous when all parties are available.

There are many use cases where asynchronous is a must, for example..

If your going to a doctor next week and make an appt, he might request your medical records anytime between scheduling the appt. and actually showing up to review them.
