### ISSUE TITLE
What operations must a did support to be usable with DWNs?

### ISSUE THREAD

**Issue by ianconsolata** [decentralized-identity/decentralized-web-node#168]
The conversation about `did:pkh` and support for MetaMask / Ethereum brought up the fact that `did:pkh` cannot sign over arbitrary json data, making it (currently) unsuitable for use with DWNs. Similarly, `did:key` does not support updating the did document and lacks a `service` section, so it would also be unsuitable for DID-relative URL resolution. Is there a list of the operations and capabilities that a specific did implementation must support to be compatible with DWNs?

**Comment by mweel1** [comment]
One question I have around  DID functionality is resolution to an DWN node.  If there are many replicated nodes, how does the DID resolver know which one to send the requestor too?

**Comment by serverwentdown** [comment]
I would imagine using `did:ethr` or `did:web` in place of `did:pkh` and `did:key`. An app might log in with Ethereum and treat the address as part of `did:ethr`.

**Comment by ianconsolata** [comment]
> One question I have around DID functionality is resolution to an DWN node. If there are many replicated nodes, how does the DID resolver know which one to send the requestor to?

The DID resolver doesn't send the requester anywhere, it just resolves the DID document. In the DID document there is a `service` section, where all the DWN nodes are listed. The DWN SDK then chooses one and makes a request to it. All should be able to support any request, but the SDK should try them in order. The expectation is that the more robust / high availability / primary nodes would be listed first, and the ones later in the list are for redundancy if first few nodes are busy or unavailable.

> I would imagine using did:ethr or did:web in place of did:pkh and did:key. An app might log in with Ethereum and treat the address as part of did:ethr.

Does did:ether support updating the did document?

**Comment by jrhender** [comment]
@ianconsolata 
> Does did:ether support updating the did document?

Yes https://github.com/decentralized-identity/ethr-did-resolver/blob/master/doc/did-method-spec.md#update

**Comment by LiranCohen** [comment]
This sounds correct, in order to be able to utilized DWNs, the DID method must support service endpoints.
