### ISSUE TITLE
Mismatch between attributes in Request object

### ISSUE THREAD

**Issue by WilliamTheHippo** [decentralized-identity/decentralized-web-node#178]
Right now, the instructions for constructing a `Request` object ([§7.1.3](https://identity.foundation/decentralized-web-node/spec/#request-construction)) contain this requirement:

> The `Request` Object **MUST** include an `id` property, and its value **MUST** be an RFC4122 UUID (Version 4) string to identify the request.

However, the `POST` request example below doesn't contain such a property, nor does either the example or list of requirements of a `Request` object given in [§8](https://identity.foundation/decentralized-web-node/spec/#request-objects). Is this a mistake? Should that first **MUST** be a **MAY**, should `id` properties be added in these places, or should the line requiring them be removed entirely?

**Comment by mistermoe** [comment]
It's a mistake, the line should be removed entirely: https://github.com/decentralized-identity/decentralized-web-node/issues/165
