### ISSUE TITLE
Will directories and AI drive centralization of Decentralized Web Nodes?

### ISSUE THREAD

**Issue by agropper** [decentralized-identity/decentralized-web-node#186]
The [Abstract](https://identity.foundation/decentralized-web-node/spec/#abstract) says:

> Decentralized Web Nodes are a mesh-like datastore construction that enable an entity to operate multiple nodes that sync to the same state across one another, enabling the owning entity to secure, manage, and transact their data with others without reliance on location or provider-specific infrastructure, interfaces, or routing mechanisms.

The primary goal appears to be standardize a DID service endpoint to process requests for persistent resources controlled by the DID subject. A secondary goal seems to be to avoid lock-in of that resource to a particular hosting location or service provider in the name of "decentralization".

Experience with GitHub and other multi-tenant services has shown that services peripheral to the reliable storage of the persistent resource itself such as searchable directories, issue tracking, reputation, and especially machine learning / artificial intelligence drive centralization instead. https://redecentralize.org/redigest/2022/06/ 

DIDs are designed to be effective in removing authentication as one of the peripheral services that can lead to centralization and surveillance as an unintended consequence. VCs and related functions such as zero-knowledge proofs are designed to be effective in preventing proprietary and often unaccountable reputation mechanisms. Appropriate design of standardized DID service endpoints like DWNs must continue this practice if we're to retain the value of "decentralized" as a marketing term for our work.

One mitigation for the proven risk of centralization is to separate from persistence services, services such as directory management and machine learning that depend on aggregation across many resource owners and their DIDs. Another mitigation separates the DID-associated request endpoint from the resource access endpoint and encourage separate assortment of request processing (control) services and resource creation and persistence (processing).

If there is consensus on these centralization risks within this group, then we must discuss and incorporate appropriate mitigations. If not, then other workgroups and market mechanisms will create alternative ways to use the DID service endpoint.

**Comment by LiranCohen** [comment]
DWNs are multi-master replicas which you can run anywhere you'd like. You could run multiple of them yourself, or rely on service providers as well.

I'm not really sure I understand the centralization risk wrt AI specifically, if you could elaborate maybe that would help.

Closing for now, please re-open if there are any further clarifications, updates or questions.
