### ISSUE TITLE
quick fix for some broken grammar and punctuation 

### ISSUE THREAD

**Issue by TallTed** [decentralized-identity/decentralized-web-node#204]
Presuming I've deciphered what was meant by the existing text at https://identity.foundation/decentralized-web-node/spec/#initial-collection-entry —

> 1. Generate the message’s _[Entry ID](https://identity.foundation/decentralized-web-node/spec/#collection-entry-id)_ by performing the _[Record ID Generation Process](https://identity.foundation/decentralized-web-node/spec/#recordid-generation)_.
>    * IF the generated _Entry ID_ matches the `recordId` value of the message it is the _[Initial Entry](https://identity.foundation/decentralized-web-node/spec/#initial-collection-entry)_ for a record, store the entry as the _[Initial Entry](https://identity.foundation/decentralized-web-node/spec/#initial-collection-entry)_ for the record if no _[Initial Entry](https://identity.foundation/decentralized-web-node/spec/#initial-collection-entry)_ exists and cease any further processing.
>    * ELSE the message may be an overwriting entry for the record; continue processing.

— that text should be changed to —

> 1. Generate the message’s _[Entry ID](https://identity.foundation/decentralized-web-node/spec/#collection-entry-id)_ by performing the _[Record ID Generation Process](https://identity.foundation/decentralized-web-node/spec/#recordid-generation)_.
>    * IF the generated _Entry ID_ matches the `recordId` value of the message —
>      * IF no _[Initial Entry](https://identity.foundation/decentralized-web-node/spec/#initial-collection-entry)_ exists, store this entry as the _[Initial Entry](https://identity.foundation/decentralized-web-node/spec/#initial-collection-entry)_ for the record, and cease any further processing.
>      * ELSE the message may be an overwriting entry for the record; continue processing.
>    * ELSE continue processing.

**Comment by andorsk** [comment]
Here's the PR : https://github.com/decentralized-identity/decentralized-web-node/pull/233
