### ISSUE TITLE
Change References from IPFS to IPLD

### ISSUE THREAD

**Issue by moisesja** [decentralized-identity/decentralized-web-node#210]
The spec has a couple of old references to IPFS:

"For various purposes Messages rely on IPFS CIDs and DAG APIs...
"all Messages MUST be committed to an IPFS DAG in a tree allocated to the DID..."

After discussing with Daniel, these should refer to IPLD as they cause confusion into thinking that DWNs messages are stored in IPFS

**Comment by andorsk** [comment]
DIF call: Moises to send PR on this.
