### ISSUE TITLE
Add Technology Comparison Matrix to Companion Guide

### ISSUE THREAD

**Issue by andorsk** [decentralized-identity/decentralized-web-node#212]
Add comparison matrix to companion guide. @moisesja has offered to help with this.

**Comment by andorsk** [comment]
Discuss on DIF call: List of comparables, SOLID PODS, KERI, 
https://en.wikipedia.org/wiki/Personal_data_service
https://github.com/benri-io/decentralized-web-node/blob/afdfee75482d66c2ce807a34de8f2e316fb1d8d6/docs/companion_guide.md#dwn-vs-didcomm-vs-keri

Fission and Peergos and Ceramic : to add in.

**Comment by andorsk** [comment]
@moisesja can you comment on this ticket so I can assign you?

**Comment by moisesja** [comment]
Began drafting the comparison.

**Comment by moisesja** [comment]
PR is ready.

**Comment by andorsk** [comment]
this was done #226 . Closing this.
