### ISSUE TITLE
inaccurate description of Solid

### ISSUE THREAD

**Issue by pchampin** [decentralized-identity/decentralized-web-node#299]
The description on Solid (https://identity.foundation/decentralized-web-node/guide/v0.0.1/#personal-data-stores) contains a number of inaccurate statements:

* "Open Specification incubated by Inrupt and now the [W3C](https://github.com/solid/specification/)"
  The Solid specification was first incubated at MIT, then by the [Solid Project](https://github.com/solid), then by the [W3C Solid Community Group](https://www.w3.org/community/solid/). At no point was it in the sole custody of Inrupt.
  
* "A Solid Pod server becomes an OpenID provider."
  Nothing in Solid forces the storage ("pod") provider and the identity provider to be the same server.
  
 * "Data is encoded in graphs using N3 notation (a superset of RDF triples)."
   Data in Solid is typically encoded in RDF, using either the Turtle or JSON-LD format (see [§5.5 Resource representation](https://solidproject.org/TR/protocol#resource-representations)).
   N3 (more specifically a subset thereof) is only used as a format for [PATCH](https://solidproject.org/TR/protocol#server-patch-n3-accept).

* "Query Capabilities: The HTTP GET method allows for N3 Path Syntax."
  I'm not sure what this is referring to, but I can not find any reference to this in the [current spec](https://solidproject.org/TR/protocol) nor in the [editor's draft](https://solidproject.org/ED/protocol).

**Comment by andorsk** [comment]
Related to #298

**Comment by andorsk** [comment]
@pchampin was this solved sufficiently in #298?

**Comment by pchampin** [comment]
yes, thanks
