### ISSUE TITLE
what is this hub of identity?

### ISSUE THREAD

**Issue by TallTed** [decentralized-identity/decentralized-web-node#60]
The blank
https://github.com/decentralized-identity/identity-hub#readme
and the 404 at
https://identity.foundation/identity-hub/
are entirely uninformative.

Surfing through the code directories of this repo doesn't help much more.

And [the CCG homepage](https://www.w3.org/community/credentials/) doesn't mention this task-force/committee/sub-group.

These seem like important things to rectify sooner than later.

**Comment by csuwildcat** [comment]
@TallTed  the spec is intentionally a sparse Strawman, specifically so we can start making it more informative and build out the content/language that answers these questions and define the necessary components. I hope the CCG will list both the initiatives, but I don't control the homepage you linked to.

**Comment by bmann** [comment]
See #75 for naming, I agree it doesn't quite fit right now.

**Comment by TallTed** [comment]
I see that the link out from the ABOUT on this repo, https://identity.foundation/identity-hub/spec, now gets to the strawman spec -- but that strawman spec says its "Latest Draft" is at https://identity.foundation/identity-hub (without the last path segment, `/spec`) which gets a lovely 404.

**Comment by csuwildcat** [comment]
I think the group would welcome a PR to address this.

**Comment by TallTed** [comment]
> [@csuwildcat said] I think the group would welcome a PR to address this.

I think someone in the group must know some of the answers I've been asking for, in order to write the document(s) I want to read, in order to learn those answers, without which I cannot write a useful PR.

That said, I guess it could just be a copy from https://github.com/decentralized-identity/edv-spec since both that and this apparently sprang from the same discussions and now alternate weeks for concalls...

**Comment by TallTed** [comment]
I think the concall logs, [such as they are](https://hackmd.io/UsGtEYJ9TdmevbFyJHzfRA) (for one thing, I cannot tell whether that page is supposed to hold minutes of *all* calls for this work item), should also be linked from the README, and some clarity added *there* (not least of which, putting all dates into ISO standard YYYY-MM-DD form, instead of having them look like they're document heading numbers)...

**Comment by csuwildcat** [comment]
Closing now, as this appears to be in order. Please open a new issue if anything mentioned needs further consideration.
