### ISSUE TITLE
Define and agree upon design goals

### ISSUE THREAD

**Issue by wyc** [decentralized-identity/decentralized-web-node#62]
We need to specify design goals, and/or [design and decision criteria](https://web.mit.edu/course/21/21.guide/designcr.htm), for Identity Hubs. These should comprehensively describe what is in or (more importantly) out of scope for Identity Hubs, and roughly how the in-scope items are organized.

I hope to make progress on the working group calls--this should certainly be a group decision, but I will self-assign to make sure someone is driving it forward.

Closes #60

**Comment by TallTed** [comment]
I don't quite understand how this solves the problem of this repo's [README](https://github.com/decentralized-identity/identity-hub#readme) being useless (as it is entirely empty)...  But maybe you're thinking updating the README is implicit in the above?  I suggest making all implicit expectations explicit.

**Comment by csuwildcat** [comment]
We did this as a matter of course for the general scope of the SDS WG, initially in the joint Hub/EDV group. Closing now, as this is something we can pull in from there as an appendix item.
