### ISSUE TITLE
Please change the name from "Identity Hub" to "Personal Data Store"

### ISSUE THREAD

**Issue by selfissued** [decentralized-identity/decentralized-web-node#75]
"Personal Data Store" is the long-standing industry term for this kind of thing.  Please let's not invent a new term.

If people believe that the scope is wider than just "Personal", then use the name "Data Store".  But please let's not unnecessarily create confusion by creating a new term.  There's still time to correct this.

**Comment by bmann** [comment]
I agree that "Personal Data Store" is the overarching term, including things like what SOLID Protocol is doing. I'd love to reserve that term for the "generic" aspect of having a big tent where we have a lot of people running personal data stores.

In the context of the standard, I'd suggested Distributed Data Storage and Relay, as I think that's the scope.

Distributed rather than decentralized because there may be multiple "federated" instances of data rather than full decentralization.

Not sure if Relay is needed in there, but some of it is about the transfer of data itself.

@csuwildcat is the right process to PR the spec itself? Where do we finalize this bike shed?

**Comment by csuwildcat** [comment]
@bmann +1 to Distributed Data Storage & Relay, because other interfaces, like Actions, Permissions, etc. will end up relaying messages/data to others in a push style, so it's not just a traditional datastore with rather static files.

**Comment by TallTed** [comment]
I think I'm in favor of "Distributed Data Storage" with or without "& Relay"...

... but I'm still not sure I understand what the purpose(s) or end goal(s) of this effort are, and #60 still applies.

**Comment by csuwildcat** [comment]
@TallTed the reason for "Relay" is that this isn't some dumb file storage db, it will actively relay various actionable messages between peers who interact by pushing messages through it. This is much like Textile's Inbox feature/concept, thus I'd like the name to distinguish it from datastores that just house files.

**Comment by TallTed** [comment]
@csuwildcat — Sure. All of which, and more, could *and should* be put into the README, with appropriate disclaimers about possible impermanence. Assuming that the rest of the (task force? subcommittee? something else?) membership concurs.

**Comment by expede** [comment]
Also a +1 to something in the vein of Distributed Data Storage & Relay

**Comment by agropper** [comment]
I think the central issue is agency over storage. Does agency (in the sense of control) over access to distributed data require that the data be under my possession (what's the difference between Facebook and Solid in this respect?). 

If Hubs are to be different from Agents as it relates to control over access to storage, our name should help people understand the difference.

**Comment by csuwildcat** [comment]
The WG came to consensus on a new name: Decentralized Web Node. This is now reflected in the spec as well as the repo name. Closing as completed!

**Comment by TallTed** [comment]
> The WG came to consensus on a new name:

Would you please provide a link to where/when this consensus was realized? (Typically, meeting minutes and/or links to relevant mailing list threads are sufficient.)

**Comment by csuwildcat** [comment]
Yep, we talked about it on the call yesterday; proposed the name, and everyone liked it for describing the scope of what a Hub was always about (people often thought Identity meant it only did old school identity cred stuff, and others thought Hub meant it was a centralized protocol). There is a recording of the call available in the WG calls captured by DIF.

**Comment by TallTed** [comment]
@csuwildcat -- I understand and agree that the name "Identity Hub" has caused confusion about what this thing is meant to be or do.  I'm not sure that "Decentralized Web Node" is a lot better, but maybe it will grow on me.  Toward that end, I'd like to read and/or listen to the discussion that brought this change.  I don't have time to read and/or listen to lots of unrelated discussion while pursuing understanding of this change.  I'm sure you can find the URI for the minutes (preferable) and/or recording (and hopefully a relevant timestamp therein) faster than I can.  Please do so and provide it.

**Comment by csuwildcat** [comment]
@TallTed here is the sheet with links to the WG recordings: https://docs.google.com/spreadsheets/d/1wgccmMvIImx30qVE9GhRKWWv3vmL2ZyUauuKx3IfRmA/edit#gid=85275820

**Comment by TallTed** [comment]
Recordings should not be considered a replacement for meeting minutes. They are not indexable, searchable, etc. [62 minutes of recording](https://us02web.zoom.us/rec/share/9ozHQlJulv2sYY6HahV0bjvvyu9HLEOp-uib0Ag4AoTdyROvUeCrXVd1GIkTDsnY.Zl71ufrNZyRHVI6l) is a lot to plow through, to locate what is likely to be just a few minutes of discussion on this renaming topic.

**Comment by csuwildcat** [comment]
It's all in the first 15 minutes after speaking begins.
