### ISSUE TITLE
Use `nonce` instead of `timestamp`in "9.1 Last-Write Replace"

### ISSUE THREAD

**Issue by oed** [decentralized-identity/decentralized-web-node#80]
The use of `timestamp` in the DAG-JOSE header can be problematic. If a users computer has a miscsonfigured system clock they may end up with a timestamp that is in the future and it will be impossible to replace the object for a (long) while. Also, `timestamp` is not a registered header property in [IANA](https://www.iana.org/assignments/jose/jose.xhtml). We could however use `nonce` where the highest nonce would always be the one that's selected to mitigate these issues.

Note: we do something similar in the suggested [DID Publish](https://github.com/ceramicnetwork/CIP/issues/105) stream type in Ceramic. We also use the URL property to indicate which object is being replaced.

**Comment by csuwildcat** [comment]
@oed good point, was just looking for highest incremented change anyway, so whatever standard value format is best seems fine.

**Comment by bumblefudge** [comment]
is that a nonce or just a monotonic counter?

**Comment by oed** [comment]
@bumblefudge just an incrementing number similar to the transaction nonce in ethereum for example.

**Comment by csuwildcat** [comment]
Has been amended in the current spec, closing as completed.
