### ISSUE TITLE
Add use cases link

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/decentralized-web-node#83]
https://identity.foundation/edv-use-cases/

**Comment by csuwildcat** [comment]
Expound upon the use cases with app-like entries and open data publication scenarios.

**Comment by gobengo** [comment]
Where should it be added?

**Comment by andorsk** [comment]
This will be in the companion guide. Proposal to close this issue as this is directly mentioned as a section in the companion guide. https://github.com/decentralized-identity/decentralized-web-node/blob/c1ffec5b9b62d493adae16a605878ded54e36aca/docs/companion_guide_stripped.md#example-use-cases

**Comment by andorsk** [comment]
Discussed on DIF: part of the companion guide. To close.
