### ISSUE TITLE
Missing details how to address different hubs

### ISSUE THREAD

**Issue by mahoekst** [decentralized-identity/decentralized-web-node#90]
Reading the spec I see this addressing format did:example:123 + ?service=IdentityHub + &relativeRef=/?message= + { MESSAGE_BODY }

It's unclear how to address different hubs this way?

**Comment by kdenhartog** [comment]
I'd expect that this would point at a service endpoint in the did document that would have an id property of `did:example:123#IdentityHub`. So if you want to make this point at a different service endpoint, you'd replace the `IdentityHub` query parameter value.

**Comment by gobengo** [comment]
@mahoekst Does @kdenhartog's answer provide some clarity?
