### ISSUE TITLE
Handle a larger variety of HTTP conditions in Hub implementation lib

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/decentralized-web-node#93]

**Comment by Identitywoman** [comment]
@csuwildcat we don't know what this means - please elaborate further.

**Comment by gobengo** [comment]
? https://developer.mozilla.org/en-US/docs/Web/HTTP/Conditional_requests

**Comment by andorsk** [comment]
Discussed on DIF call with @csuwildcat , not applicable anymore. Closing.
