### ISSUE TITLE
Specify encoder for messageId

### ISSUE THREAD

**Issue by xinaxu** [decentralized-identity/decentralized-web-node#98]
In point 3 of [Chapter 9.2](https://identity.foundation/identity-hub/spec/#response-objects), it says the messageId must be V1 CID of the message, however it does not specify the encoder, can it be explicitly specified to use DAG-CBOR encoding?

**Comment by LiranCohen** [comment]
I think this is already solved:

If attestation of an object is permitted, the payload MAY include an attestationCid property, and its value MUST be the stringified [Version 1 CID](https://docs.ipfs.io/concepts/content-addressing/#identifier-formats) of the [DAG CBOR](https://github.com/ipld/specs/blob/master/block-layer/codecs/dag-cbor.md) encoded attestation string.


Please re-open if there was a misunderstanding.
